[metadata]
description-file = README.rst

[bdist_wheel]
universal=1

[tool:pytest]
testpaths = pwdtk

[flake8]
max_line_length = 120

[coverage:run]
# the action reporting the coverage on github needs relative paths
relative_files = true
source = pwdtk
omit =
    pwdtk/migrations/*
    pwdtk/testproject/*
    pwdtk/tests/*
    pwdtk/test_settings.py
    pwdtk/testviews.py
