[tox]
# only the long term support releases of django are tested
envlist=py{38,39}-django{22,32,42}
        py312-django{42,52}
        py312-lint



[testenv]
deps =
    django22: -r requirements/tox_dj22.txt
    django31: -r requirements/tox_dj31.txt
    django32: -r requirements/tox_dj32.txt
    django42: -r requirements/tox_dj42.txt
    django52: -r requirements/tox_dj52.txt

setenv =
    PWDTK_TOX_ENVNAME = {envname}
    django22: DJANGO_SETTINGS_MODULE = pwdtk.testproject.dj22.settings
    django31: DJANGO_SETTINGS_MODULE = pwdtk.testproject.dj31.settings
    django32: DJANGO_SETTINGS_MODULE = pwdtk.testproject.dj32.settings
    django42: DJANGO_SETTINGS_MODULE = pwdtk.testproject.dj42.settings
    django52: DJANGO_SETTINGS_MODULE = pwdtk.testproject.dj52.settings

commands=
         # python -c "import os ; print(os.environ.get('DJANGO_SETTINGS_MODULE', '??'))"
         pip install -U pip
         pip install pytest
         pip freeze
         pip check
         pytest {envsitepackagesdir}/pwdtk {posargs}

[testenv:py312-lint]
commands=
         pip install -U pip
         pip install -U flake8
         python -m flake8 pwdtk
