# Generated by Django 2.2.28 on 2024-03-05 09:40

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdtk', '0008_auto_20230905_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwddata',
            name='first_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pwddata',
            name='password_history',
            field=django_jsonfield_backport.models.JSONField(default=list),
        ),
    ]
