# Generated by Django 2.2.28 on 2025-03-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdtk', '0009_auto_20250320_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwddata',
            name='locked_until',
            field=models.DateTimeField(null=True),
        ),
    ]
