# Generated by Django 2.2.28 on 2024-03-05 09:40

from django.db import migrations, models
import django_jsonfield_backport.models

from pwdtk.models import json_field


def set_first_password_false(apps, schema_editor):
    db = schema_editor.connection.alias
    PwdData = apps.get_model('your_app_name', 'PwdData')
    PwdData.objects.using(db).all().update(first_password=False)


class Migration(migrations.Migration):

    dependencies = [
        ('pwdtk', '0010_auto_20250328_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwddata',
            name='first_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pwddata',
            name='password_history',
            field=json_field(default=list),
        ),
        migrations.RunPython(
            set_first_password_false,
            reverse_code=migrations.RunPython.noop
        ),
    ]
