# Generated by Django 4.2.20 on 2025-05-19 13:16

from django.db import migrations

from pwdtk.models import json_field


class Migration(migrations.Migration):

    dependencies = [
        ('pwdtk', '0010_auto_20250328_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwddata',
            name='password_history',
            field=json_field(default=list),
        ),
    ]
