# Generated by Django 4.2.22 on 2025-06-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwdtk', '0011_alter_pwddata_password_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwddata',
            name='lockout_count',
        ),
    ]
